# notebook
FROM jupyter/scipy-notebook

USER root
# needed for bitarray install
RUN apt-get update && apt-get install -y gcc

USER ${NB_UID}


RUN pip install \
    bitarray \
    dataset \
#    elasticsearch-dsl==2.0.0 \
    elasticsearch==6.0.0 \
    nltk \
    path.py


# Previously this docker file had the following to prebuild the matplotlib font cache
# (Otherwise the first time someone does this is a notebook, they'll see warning
# messages and have to wait.)
# However, this command fails (perhaps because of recent matplotlib changes?)
# RUN python -c "import matplotlib; matplotlib.use('TkAgg'); import matplotlib.pyplot"

COPY . /home/$NB_USER/work/

# Expect an elasticsearch server available at this host and port.
RUN sed -i "s/^\s*db_host\s*=.*$/db_host = 'elasticsearch'/" /home/$NB_USER/work/config.py
