name: CI_nbc

on: push

jobs:
  basic-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: docker build
      uses: docker/build-push-action@master
      with:
        context: ./
        push: false

  integration-test-aurum:
    runs-on: ubuntu-20.04
    timeout-minutes: 20
    steps:
      - uses: TheDataStation/integration/.github/actions/integ-aurum@master
        with:
          nbc_repository: ${{ github.repository }}
          nbc_commit: ${{ github.ref }}
